version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: npm install
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0

    steps: 
      - checkout
      - run: npm audit

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test: 
          requires:
            - build 
      - analyze: 
          requires:
            - test
